<?php
echo "<!DOCTYPE html>\n";
echo "html>\n";
echo "<head>\n";
echo "   <meta charset=\"utf-8\">\n";
echo "   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\">\n";
echo "   <title>STCC social proto</title>\n";
echo "   <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\">\n";
echo "   <link rel=\"stylesheet\" href=\"assets/css/styles.min.css\">\n";
echo "/head>\n";
echo "<body style=\"background: url(&quot;assets/img/bkgrd_oy.png&quot;) center, radial-gradient(black 66%, white 100%);\">\n";
echo "   <!-- Start: Navigation with Search -->\n";
echo "   <nav class=\"navbar navbar-light navbar-expand-md navigation-clean-search\" style=\"background: #9d0101;\">\n";
echo "       <div class=\"container\">\n";
echo "           <a class=\"navbar-brand\" href=\"#\" style=\"text-shadow: 3px 1px 3px;color: rgb(255,252,252);\">\n";
echo "               <!--Meant to redirect to home page; Requires URL--><img style=\"background: url(&quot;assets/img/Snek%20co%20transparent%20resize.png&quot;) no-repeat;background-size: contain;\">STCC Social<br></a><button data-toggle=\"collapse\" class=\"navbar-toggler\" data-target=\"#navcol-1\"><span class=\"sr-only\">Toggle navigation</span><span class=\"navbar-toggler-icon\"></span></button>\n";
echo "           <div\n";
echo "               class=\"collapse navbar-collapse\" id=\"navcol-1\" style=\"width: 663px;\">\n";
echo "               <ul class=\"nav navbar-nav\">\n";
echo "                   <li class=\"nav-item\"><a class=\"nav-link active\" href=\"https://www.stcc.edu/\" style=\"color: rgb(228,231,109);text-shadow: 2px 1px 4px;\"><strong>STCC Main</strong></a></li>\n";
echo "                   <li class=\"nav-item\"><a class=\"nav-link active\" href=\"https://advisorweb.stcc.edu/WebAdvisor/WebAdvisor?TYPE=M&amp;PID=CORE-WBMAIN&amp;TOKENIDX=1017827741\" style=\"color: rgb(228,231,109);text-shadow: 2px 1px 4px;\"><strong>WebAdvisor</strong></a></li>\n";
echo "                   <li\n";
echo "                       class=\"nav-item\"><a class=\"nav-link active\" href=\"https://stcc.blackboard.com/webapps/login/\" style=\"color: rgb(228,231,109);text-shadow: 2px 1px 4px;\"><strong>Blackboard</strong></a></li>\n";
echo "               </ul>\n";
echo "       </div>\n";
echo "       </div>\n";
echo "   </nav>\n";
echo "   <!-- End: Navigation with Search -->\n";
echo "   <!-- Start: 2 Rows 1+1 Columns -->\n";
echo "   <div>\n";
echo "       <div class=\"container\">\n";
echo "           <div class=\"row\">\n";
echo "               <div class=\"col\"><label class=\"col-form-label\" style=\"color: rgb(17,19,20);text-shadow: 1px 2px 17px;\"><strong>Title</strong></label></div>\n";
echo "               <div class=\"col-md-12\">\n";
echo "                   <div class=\"form-group\"><input type=\"text\" style=\"width: 628px;\"></div>\n";
echo "               </div>\n";
echo "           </div>\n";
echo "           <div class=\"row\">\n";
echo "               <div class=\"col\"></div>\n";
echo "               <div class=\"col-md-12\"><textarea style=\"width: 626px;height: 297px;\"></textarea></div>\n";
echo "           </div>\n";
echo "       </div>\n";
echo "   </div>\n";
echo "   <!-- End: 2 Rows 1+1 Columns -->\n";
echo "   <!-- Start: 1 Row 4 Columns -->\n";
echo "   <div>\n";
echo "       <div class=\"container\">\n";
echo "           <div class=\"row\">\n";
echo "               <div class=\"col-md-3\"></div>\n";
echo "               <div class=\"col-md-3\"></div>\n";
echo "               <div class=\"col\"><button class=\"btn btn-primary\" type=\"button\">Post</button></div>\n";
echo "           </div>\n";
echo "       </div>\n";
echo "   </div>\n";
echo "   <!-- End: 1 Row 4 Columns -->\n";
echo "   <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n";
echo "   <script src=\"https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/js/bootstrap.bundle.min.js\"></script>\n";
echo "/body>\n";
echo "</html>\n";
?>