<?php
echo "<!DOCTYPE html>\n";
echo "html class=\"text-justify\">\n";
echo "<head>\n";
echo "   <meta charset=\"utf-8\">\n";
echo "   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\">\n";
echo "   <title>Home - Brand</title>\n";
echo "   <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\">\n";
echo "   <link rel=\"stylesheet\" href=\"assets/fonts/font-awesome.min.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"assets/fonts/ionicons.min.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"assets/css/Footer-Clean.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"assets/css/Navigation-with-Search.css\">\n";
echo "   <link rel=\"stylesheet\" href=\"assets/css/untitled.css\">\n";
echo "/head>\n";
echo "<body>\n";
echo "   <nav class=\"navbar navbar-light navbar-expand bg-light navigation-clean\">\n";
echo "       <div class=\"container\"><a class=\"navbar-brand\" href=\"#\" style=\"filter: contrast(130%);\">STCC Creates</a><button data-toggle=\"collapse\" class=\"navbar-toggler\" data-target=\"#navcol-1\"></button>\n";
echo "           <div class=\"collapse navbar-collapse\" id=\"navcol-1\"><a class=\"btn btn-primary ml-auto\" role=\"button\" href=\"#\">Sign In</a></div>\n";
echo "       </div>\n";
echo "   </nav>\n";
echo "   <header data-toggle=\"tooltip\" data-bs-tooltip=\"\" class=\"masthead text-white text-center\" style=\"background: url(&quot;assets/img/blutint.png&quot;);\">\n";
echo "       <header class=\"overlay\"></header>\n";
echo "       <div class=\"container\">\n";
echo "           <div class=\"row\">\n";
echo "               <div class=\"col-5 col-sm-4 col-md-5 col-lg-2 col-xl-4 offset-0 offset-lg-6 offset-xl-7 mx-auto\">\n";
echo "                   <h6 class=\"mb-5\" style=\"text-shadow: 0px 0px 2px;\"><strong>Danger Noodles present</strong><br></h6><img class=\"img-fluid visible\" data-toggle=\"tooltip\" data-bs-tooltip=\"\" data-placement=\"right\" style=\"background: url(&quot;assets/img/Snek%20co%20transparent%20resize.png&quot;) center / cover no-repeat;\" src=\"assets/img/Snek%20co%20transparent%20resize.png\">\n";
echo "                   <figure\n";
echo "                       class=\"figure\"></figure>\n";
echo "               </div>\n";
echo "               <div class=\"col-xl-9 offset-lg-4 mx-auto\" style=\"border-style: none;text-shadow: 3px 2px;text-align: center;\">\n";
echo "                   <h1 class=\"mb-5\" style=\"width: 323px;text-align: justify;height: 33px;\">STCC Social</h1>\n";
echo "               </div>\n";
echo "               <div class=\"col-md-10 col-lg-8 col-xl-7 mx-auto\">\n";
echo "                   <form>\n";
echo "                       <div class=\"form-row\">\n";
echo "                           <div class=\"col-12 col-md-9 mb-2 mb-md-0\"><input class=\"form-control form-control-lg\" type=\"email\" placeholder=\"Enter your email...\"></div>\n";
echo "                           <div class=\"col-12 col-md-3\"><button class=\"btn btn-primary btn-block btn-lg\" type=\"submit\">Sign up!</button></div>\n";
echo "                       </div>\n";
echo "                   </form>\n";
echo "               </div>\n";
echo "           </div>\n";
echo "       </div>\n";
echo "   </header>\n";
echo "   <!-- Start: Footer Clean -->\n";
echo "   <div class=\"footer-clean\">\n";
echo "       <footer>\n";
echo "           <div class=\"container\">\n";
echo "               <div class=\"row justify-content-center\">\n";
echo "                   <!-- Start: Services -->\n";
echo "                   <div class=\"col-sm-4 col-md-3 item\"><img style=\"background: url(&quot;Springfield_Technical_Community_College_(STCC)_seal.png&quot;) center no-repeat;\"></div>\n";
echo "                   <!-- End: Services -->\n";
echo "                   <!-- Start: About -->\n";
echo "                   <div class=\"col-sm-4 col-md-3 item\">\n";
echo "                       <h3>About</h3>\n";
echo "                       <ul>\n";
echo "                           <li></li>\n";
echo "                           <li><a href=\"#\">Team</a></li>\n";
echo "                           <li><a href=\"#\">Home</a></li>\n";
echo "                       </ul>\n";
echo "                   </div>\n";
echo "                   <!-- End: About -->\n";
echo "                   <!-- Start: Careers -->\n";
echo "                   <div class=\"col-sm-4 col-md-3 item\">\n";
echo "                       <h3></h3>\n";
echo "                       <ul>\n";
echo "                           <li></li>\n";
echo "                           <li></li>\n";
echo "                           <li><a href=\"#\"></a></li>\n";
echo "                       </ul>\n";
echo "                   </div>\n";
echo "                   <!-- End: Careers -->\n";
echo "                   <!-- Start: Social Icons -->\n";
echo "                   <div class=\"col-lg-3 item social\"><a href=\"#\"><i class=\"icon ion-social-facebook\"></i></a><a href=\"#\"><i class=\"icon ion-social-twitter\"></i></a><a href=\"#\"><i class=\"icon ion-social-snapchat\"></i></a><a href=\"#\"><i class=\"icon ion-social-instagram\"></i></a>\n";
echo "                       <p class=\"copyright\">Danger Noodles © 2020</p>\n";
echo "                   </div>\n";
echo "                   <!-- End: Social Icons -->\n";
echo "               </div>\n";
echo "           </div>\n";
echo "       </footer>\n";
echo "   </div>\n";
echo "   <!-- End: Footer Clean -->\n";
echo "   <script src=\"assets/js/jquery.min.js\"></script>\n";
echo "   <script src=\"assets/bootstrap/js/bootstrap.min.js\"></script>\n";
echo "   <script src=\"assets/js/bs-init.js\"></script>\n";
echo "/body>\n";
echo "</html>\n";
?>